# Configuration and constants for StreetRace Manager

# Roles
DRIVER = "driver"
MECHANIC = "mechanic"
STRATEGIST = "strategist"
VALID_ROLES = [DRIVER, MECHANIC, STRATEGIST]

# Skill levels (0-100)
MIN_SKILL = 0
MAX_SKILL = 100

# Vehicle conditions
VEHICLE_CONDITION_GOOD = "good"
VEHICLE_CONDITION_DAMAGED = "damaged"
VEHICLE_CONDITION_DESTROYED = "destroyed"

# Race types
RACE_TYPE_STREET = "street"
RACE_TYPE_CIRCUIT = "circuit"
RACE_TYPE_DRAG = "drag"

# Mission types
MISSION_TYPE_DELIVERY = "delivery"
MISSION_TYPE_RESCUE = "rescue"
MISSION_TYPE_HEIST = "heist"

# Prize money
RACE_PRIZE_FIRST = 5000
RACE_PRIZE_SECOND = 3000
RACE_PRIZE_THIRD = 1500

# Reputation thresholds
REPUTATION_THRESHOLD_BRONZE = 100
REPUTATION_THRESHOLD_SILVER = 500
REPUTATION_THRESHOLD_GOLD = 1000
REPUTATION_THRESHOLD_PLATINUM = 2000

# Fuel consumption per race
FUEL_CONSUMPTION_STREET = 20
FUEL_CONSUMPTION_CIRCUIT = 30
FUEL_CONSUMPTION_DRAG = 40

# Damage percentages from race
RACE_DAMAGE_MINOR = 10
RACE_DAMAGE_MODERATE = 25
RACE_DAMAGE_SEVERE = 50
